// Actions
export const SET_SOURCE_REQUEST = 'SET_SOURCE_REQUEST';
export const SET_SOURCE_SUCCESS = 'SET_SOURCE_SUCCESS';
export const SET_SOURCE_FAILURE = 'SET_SOURCE_FAILURE';
export const ZOOM_IN = 'ZOOM_IN';
export const ZOOM_OUT = 'ZOOM_OUT';
export const RESET_SCALE = 'RESET_SCALE';
export const DOWNLOAD_SUCCESS = 'DOWNLOAD_SUCCESS';
