name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install, Build & Test.
      run: |
        yarn install
        yarn test
        yarn lint
        yarn build:production
      env:
        CI: true
